### PR TITLE
Updates to make the webcode work with the new regulation api

### PR DESCRIPTION
**Pull request by mn1**
These should make the webcode work with the new regulation api on master as soon as this pull request:

https://github.com/Ensembl/ensembl/pull/216

has been merged into Ensembl core.

### CODE REVIEW

**Comment by ens-ap5** [comment]
Thanks, Michael - I'll merge it in after db handover, so that we don't break the web team's sandboxes

**Comment by ens-st3** [comment]
Are the core patches that are needed to get this working on staging committed ?

**Comment by mn1** [comment]
Core has merged my pull request. It should all work.

**Comment by ens-st3** [comment]
@ens-ap5 - could you take a look at this conflict ?

**Comment by ens-ap5** [comment]
Which conflict? I did the merge ages ago.

Anne

**Comment by ens-ap5** [comment]
OK, done

**Pull request merged**
