### PR TITLE
genome_db.assembly_default has been removed in e82

### PR DESCRIPTION
**Pull request by muffato**
Also, we can simply take all the GenomeDBs regardless of their first/last_release status

### CODE REVIEW

**Comment by muffato** [comment]
BTW, this function only does direct SQL queries on the database handle. Is it possible to have a Compara DBAdaptor instead ? We could then move the queries to our side and it would be easier to maintain

**Comment by ens-ap5** [comment]
Hi Matthieu

If you want to have them in the API, that would be fine. We do use a lot of SQL in ConfigPacker because it’s grabbing things like track summaries that are not needed anywhere else and hence have historically not been incorporated into the respective APIs, but it does make the code harder to maintain.

Cheers

Anne

**Comment by muffato** [comment]
ah, you think it would make things harder :)
My question mainly is whether it is possible to have a DBAdaptor. We don't need to move the code, but making API calls would make the ConfigPacker more resilient to schema changes (and slightly slower)

**Comment by ens-ap5** [comment]
I meant that using SQL makes ConfigPacker harder for the webteam to maintain, because we have to keep up with schema changes.

Anne

**Comment by muffato** [comment]
right, we're on the same line, then :)
This time, I just forgot to check if the schema was directly used by other repos, but I'll add a note to our SOP so that we don't miss it next time

**Pull request merged**
