### PR TITLE
Fix invalid module import

### PR DESCRIPTION
**Pull request by veidenberg**
### Description
Remove invalid module import syntax that is generating server errors.
See [this slack thread](https://genomes-ebi.slack.com/archives/C0MUF0C3Y/p1729703830150509) for context.

### Sandbox
http://wp-np2-1d.ebi.ac.uk:1640

### CODE REVIEW

**Review by azangru — APPROVED** [review]

**Comment by azangru** [comment]
Actually, I am confused now.

If this is in webcode, and if this is for displaying the bottom panel, then wouldn't it have broken earlier and everywhere if it were truly broken?

Do you have a sandbox where this code change could be tested?

**Comment by veidenberg** [comment]
I cannot see any difference between the sandbox and live (e.g. [this](http://wp-np2-1d.ebi.ac.uk:1680/Rattus_norvegicus/Location/View?r=5%3A62797383-63627669) and [this](https://www.ensembl.org/Rattus_norvegicus/Location/View?r=5%3A62797383-63627669)), but at least no code errors in sandbox logs.

**Comment by azangru** [comment]
:shipit:

**Comment by veidenberg** [comment]
With debug messages I can see this part of code being executed, but switching between `/region` addition/removal doesn't seem to make any difference (no error messages in the logs either way).

**Comment by azangru** [comment]
All right. :shipit:

**Comment by azangru** [comment]
For history.

The reason we decided to make this change was because of this error in the logs:

```
REQUEST(P): [served at Wed Oct 23 14:07:21 2024 by 105398 in 13ms] /Ajax/accounts_dropdown
DynamicLoaderException Exception:
  Module 'EnsEMBL::Web::Component::Location::ViewBottomNav/region' could not be loaded: Bareword "region" not allowed while "strict subs" in use at (eval 13959) line 1.
  Thrown by EnsEMBL::Web::Utils::DynamicLoader::dynamic_require in module EnsEMBL::Web::Controller::Share at /nfs/public/ro/ensweb/live/plants/www_113/ensembl-webcode/modules/EnsEMBL/Web/Controller/Share.pm on line 221
  Called by EnsEMBL::Web::Controller::Share::_get_components in module EnsEMBL::Web::Controller::Share at /nfs/public/ro/ensweb/live/plants/www_113/ensembl-webcode/modules/EnsEMBL/Web/Controller/Share.pm on line 83
  Called by EnsEMBL::Web::Controller::Share::share_create in module EnsEMBL::Web::Controller::Share at /nfs/public/ro/ensweb/live/plants/www_113/public-plugins/tools/modules/EnsEMBL/Web/Controller/Share.pm on line 45
  Called by EnsEMBL::Web::Controller::Share::share_create in module EnsEMBL::Web::Controller::Share at /nfs/public/ro/ensweb/live/plants/www_113/ensembl-webcode/modules/EnsEMBL/Web/Controller/Share.pm on line 70
  Called by EnsEMBL::Web::Controller::Share::process in module EnsEMBL::Web::Apache::SpeciesHandler at /nfs/public/ro/ensweb/live/plants/www_113/ensembl-webcode/modules/EnsEMBL/Web/Apache/SpeciesHandler.pm on line 103
  Called by EnsEMBL::Web::Apache::SpeciesHandler::handler in module EnsEMBL::Web::Apache::Handlers at /nfs/public/ro/ensweb/live/plants/www_113/ensembl-webcode/modules/EnsEMBL/Web/Apache/Handlers.pm on line 531
  Called by EnsEMBL::Web::Apache::Handlers::handler in module main at -e on line 0
  Called by (eval) in module main at -e on line 0 at /nfs/public/ro/ensweb/live/plants/www_113/ensembl-webcode/modules/EnsEMBL/Web/Exception.pm line 70.
```

**Pull request merged**
