### PR TITLE
Bugfix/unigene link

### PR DESCRIPTION
**Pull request by mehrnazcharkhchi**
## Requirements

- Filling out the template is required. Any pull request that does not include enough information to be efficiently reviewed may be rejected.
- Please consider which branch this is to be submitted against. This is usually obvious, however if it is to be applied to both a release branch nn and master then please submit it against postreleasefix/nn and let us merge it into to the two branches.

## Description

_Update the link in the EST cluster (Unigene) track Z-Menu to a retired page.

## Views affected

_http://asia.ensembl.org/Homo_sapiens/Location/View?db=core;g=ENSG00000139618;r=13:32313383-32401971
_http://ves-hx2-77.ebi.ac.uk:8786/Homo_sapiens/Location/View?db=core;g=ENSG00000139618;r=13:32315086-32400268

## Possible complications
_

## Merge conflicts
_

## Related JIRA Issues (EBI developers only)

_https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5676

### CODE REVIEW

**Comment by msmanoj** [comment]
Hi @Mehrnaz-Charkhchi , the commits list doesn't seem to look right. I think you created the `bugfix/unigene_link` checkout from `release/101` instead of `postreleasefix/101`. Can you create the bugfix checkout from `postreleasefix/101` and resubmit this PR, please?

**Comment by ens-st3** [comment]
#7747d9d is the right thing to do, but the commit message is a little misleading. TrackHubs have a specific meaning*, prob better to say here is simply 'website configuration'

* https://genome.ucsc.edu/goldenpath/help/hgTrackHubHelp.html

**Comment by mehrnazcharkhchi** [comment]
@msmanoj  Could you please check if it's OK now?
@ens-st3 Thank you, I updated the commit message.

**Comment by msmanoj** [comment]
@mehrnazcharkhchi - No, it's still the same. 
If you look here:
https://github.com/Ensembl/ensembl-webcode/pull/784/commits
it says you are trying to merge 35 commits when it should just be the commits you made.

**Comment by ens-st3** [comment]
Sorry, I meant 'Update Unigene URL in website configuration'

**Comment by mehrnazcharkhchi** [comment]
@msmanoj  Yes, you're right. I rebased again.
@ens-st3 Thanks, Done!

**Comment by imransl** [comment]
@ens-st3 @msmanoj Can we merge this PR?

**Review by msmanoj — APPROVED** [review]

**Pull request merged**
