### PR TITLE
ensembl-3875 Problem showing "Resequencing alignements

### PR DESCRIPTION
**Pull request by jkhobova**
The code expects yes/no rather than on/off

We've got two tickets regarding this that came from Ensembl #467028, Ensembl #467306 and Ensembl #466232

### CODE REVIEW

**Comment by jkhobova** [comment]
In master everything is fine. Needs to be merged to .79 only

**Comment by jkhobova** [comment]
Master is fine and release/79 is fine, but release/80 has 'on' instead of 'yes'.

**Comment by jkhobova** [comment]
Can you please merge it to release/80 as well?

**Comment by ens-hsr** [comment]
Done: d2c04741

**Comment by jkhobova** [comment]
Thank you!

**Comment by jkhobova** [comment]
Hi guys, the ticket has been reopened. I've just checked modules/EnsEMBL/Web/Component/Location/SequenceAlignment.pm on branch 80 and it has back 'on' instead of 'yes'.
Any ideas why it was changed? Can you please change it back?

**Comment by ens-ds23** [comment]
This seems to have been reverted by Anne on 28th May (4fbbef7). There seems to be some confusion over this as we're all going round chasing our tail turning things to yes->on->yes. I've done the same with our Vega plugin (where some things broke). From her comment, Anne seems to have some info on what should be going on from her commit comment, but I'm not sure either way myself. I can't find tickets, etc, associated with that latter commit. Can this wait for Anne to come back and we can talk about getting this nailed down once and for all?

**Comment by jkhobova** [comment]
I'll apply a temporary fix then and we'll wait till Anne is back. Thanks.

**Pull request merged**
