### PR TITLE
Fix minor display issue in the 'Alleles' row

### PR DESCRIPTION
**Pull request by ens-lgil**

### CODE REVIEW

**Comment by ens-st3** [comment]
As it's minor will wait a few days and then push it out together with any others we get

**Comment by ens-lgil** [comment]
Sure, no problem.
Thank you Steve

**Comment by ens-lgil** [comment]
I just added a new minor fix in the StructuralVariation ZMenu.

**Comment by ens-st3** [comment]
Sorry, missed this. Does the Zmenu fix want to go live as well ?

**Comment by ens-lgil** [comment]
Hi Steve,
Yes, please.

**Pull request merged**
