### PR TITLE
Improve zmenu for protein align features

### PR DESCRIPTION
**Pull request by msmanoj**
## Description

Added `Alignment length` and `%id` to the zmenu of protein align features.

## Views affected
http://ves-hx2-76.ebi.ac.uk:42229/Homo_sapiens/Location/View?r=17:63992802-64038237

## Related JIRA Issues (EBI developers only)

https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-2615

### CODE REVIEW

**Comment by ens-ap5** [comment]
A couple of improvements spring to mind:

1. I find it's best to wrap API calls in an eval block, because some of the methods will "throw" if they can't find data, which breaks the whole web page. Usually I create the object within an eval block, then check for the object's existence before calling any subsequent methods. Call me paranoid, but edge cases just lead to RT tickets!

2. For the %id field, it might be better to use '-' rather than undef as the fallback value, so that it's clear to the user that the data is unavailable rather than it being a bug.

**Comment by msmanoj** [comment]
@ens-ap5 I have made those two changes. Thanks

**Comment by ens-ap5** [comment]
I can't see the new values on your sandbox now - have you checked out a different branch?

**Comment by msmanoj** [comment]
Yes, sorry! I've put it back now.

**Comment by ens-ap5** [comment]
Looking good! I'll just ping Jyo since he was a requested reviewer, then merge it in.

**Comment by msmanoj** [comment]
Thanks, Anne.

**Pull request merged**
