### PR TITLE
Update regex that guesses species from query in Psychic

### PR DESCRIPTION
**Pull request by azangru**
## Description
Fixes bug that can be reproduced by the following steps:
- go to home page of ensembl site
- from the dropdown box (in the centre of the screen), select a species (doesn't matter which)
- type "amelogenin" in the search box below
Observe that the search results come for panda (because the word "amelogenin" starts with the substring "amel", which is the short code for panda).

One possible solution is to update the regex in the Psychic module that assumes that if the beginning of a query matches any species present in a species hash, then it must be a query regarding this species. The updated regex will assume that if there is a species name in the query, it will be separated from the actual query by a space.

## Views affected
Search page.

## Possible complications
Don't know

## Related JIRA Issues (EBI developers only)
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5134

### CODE REVIEW

**Comment by nicklangridge** [comment]
Just to note, using word boundary matching (`\b`) in the regex will allow matches for punctuation characters (excluding underscores and hyphens) as well as white-space. Is that intended?

**Comment by azangru** [comment]
@nicklangridge I don't really know what the behaviour of the search field is intended to be. I guess we can change `\b` to `\s` or just ` ` (`/^\Q$sp\E /`) if that's more appropriate?

**Comment by ens-ap5** [comment]
Nick's right - we don't want something like "amel.2" to redirect to panda (assuming that could be a valid gene identifier in, say, a non-vertebrate species.

I would prefer changing the \b to \s, as \E isn't even in my Perl pocket reference!

**Comment by nicklangridge** [comment]
I'm not certain either. But `\s` might be the safer option. A contrived example: Imagine we have IDs like `amel;12345`. If a user tried to search for that, the colon would match the `\b`. Admittedly, it's unlikely we have those IDs, but I don't know for sure.

**Comment by nicklangridge** [comment]
`\Q` and `\E` are used correctly there - they ensure that $sp is escaped appropriately for the regex

**Pull request merged**
