### PR TITLE
Add homoeologues to data export

### PR DESCRIPTION
**Pull request by Zhicheng-Liu**
Related to ENSEMBL-4774.

### CODE REVIEW

**Comment by Zhicheng-Liu** [comment]
Please also apply this change to release/86 and master branches.

**Comment by ens-hsr** [comment]
Where is the package EnsEMBL::Web::Component::DataExport::Homoeologs?

**Comment by Zhicheng-Liu** [comment]
It is in eg-web-common. Does it have to be in ensembl-webcode? I thought it will only be loaded when required and it is only needed in EG. But I can move it to ensembl-webcode.

**Comment by ens-hsr** [comment]
You can add a plugin for EnsEMBL::Web::Configuration::DataExport in eg-web-common and override populate_tree in that file to add this extra node.

**Comment by Zhicheng-Liu** [comment]
Closing this pull request in favour of adding the "Homoeologues" data export to the eg-web-common plugin (https://github.com/EnsemblGenomes/eg-web-common/commit/2e0abe2190cd6a255bbeb79bbf21f02a0eb4998b).

**Pull request closed without merging**
