### PR TITLE
Fix for LDPlot redirecting to LD after selecting populations

### PR DESCRIPTION
**Pull request by imran-ebi**
This fix is for ENSWEB-4360. The sandbox link is: http://ves-hx-78.ebi.ac.uk:8300/Homo_sapiens/Variation/LDPlot?db=core;pop1=373508;r=9:22125004-22126004;v=rs1333049;vdb=variation;vf=906984.

### CODE REVIEW

**Comment by ens-ma7** [comment]
@imran-ebi this change will probably break other places where the population selector is used ( for example EnsEMBL::Web::Component::Location::SelectPopulation). You can see if the following page still work for you:
http://www.ensembl.org/Homo_sapiens/Location/LD?db=core;focus=variation;pop1=373508;r=9:22115504-22135503;v=rs1333049;vdb=variation;vf=906984

maybe have an if statement to check if component is LDPlot then URL is LDPlot else LD

**Comment by imran-ebi** [comment]
@ens-ma7 Thanks for mentioning it. It did break when I checked in the LD page. I will put a check in there to insert the correct page as the action.

**Comment by imran-ebi** [comment]
@ens-ma7 I have added the check in the latest commit

**Comment by ens-ma7** [comment]
@imran-ebi the way you done it is ok but a bit long, just see if you can use $hub->action to find out what page you are currently on (i just remember it might work and might not work because of the configuration panel) and then use the action as the url.

**Comment by imran-ebi** [comment]
@ens-ma7 Your suggestions was great. The fix is now only a one liner and doesn't have any loops.

**Comment by ens-ma7** [comment]
@imran-ebi great the suggestion work but you left one unused variable in the commit ($action), can you remove it please.

**Comment by imran-ebi** [comment]
@ens-ma7 Sorry about that. I totally missed that one 😞 I have removed it now.

**Comment by imran-ebi** [comment]
@ens-ma7 There was another issue identified by @jyothishnt. Have pushed the fixed for that as well.

**Pull request merged**
