### PR TITLE
Fix tools assembly label name that broke due to previous PR (#906)

### PR DESCRIPTION
**Pull request by imransl**
## Description
The previous fix for ID History Converter assembly label (#906) broken the assembly label in other tools such as File Chameleon. This PR is a fix for that issue.

Please note that this PR is not a fix for the jobs submissions failing in ID History Converter. There is a separate ticket for it ([ENSWEB-6684](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6684)), which I am working on at the moment.

### Sandbox URL
ID History Converter: http://wp-np2-1e.ebi.ac.uk:8310/Homo_sapiens/Tools/IDMapper
File Chameleon: http://wp-np2-1e.ebi.ac.uk:8310/Homo_sapiens/Tools/FileChameleon?db=core
VCF to PED: http://wp-np2-1e.ebi.ac.uk:8310/Homo_sapiens/Tools/VcftoPed

## Views affected
ID History Converter, File Chameleon and VCF to PED

## Related JIRA Issues (EBI developers only)
[ENSWEB-6684](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6684)

### CODE REVIEW

**Review by veidenberg — CHANGES_REQUESTED** [review]
I'm afraid the input form is still broken for [BLAST ](http://wp-np2-1e.ebi.ac.uk:8310/Homo_sapiens/Tools/Blast) and [VEP](http://wp-np2-1e.ebi.ac.uk:8310/Homo_sapiens/Tools/VEP) (notice the multiple copies of dropdown and  tickbox inputs). These forms [seem to be OK](http://wp-np2-1d.ebi.ac.uk:1680/Multi/Tools/Blast?db=core) when using the commit before the IDmapper tool fix.

**Review by ens-ap5 — CHANGES_REQUESTED** [review]
Same here - the affected tools look fine, but this breaks bigger forms like BLAST.

**Comment by imransl** [comment]
@veidenberg @ens-ap5 I've fixed this issue and have pushed the changes. The fix is available in both the sandbox and debug.ensembl.org

**Review by veidenberg — APPROVED** [review]
The input forms look good now, thanks!

**Pull request merged**
