### PR TITLE
Use Bio::EnsEMBL::Gene object to get colour key

### PR DESCRIPTION
**Pull request by Zhicheng-Liu**
Instead of EnsEMBL::Web::Object::Gene ...

Fixes ENSEMBL-4805.

### CODE REVIEW

**Comment by ens-st3** [comment]
Hi - does transcript supporting evidence work with this change ?

**Comment by Zhicheng-Liu** [comment]
Hi @ens-st3, not sure about what you mean and how to test it. But this change will only affect the $gene variable at this line (https://github.com/Ensembl/ensembl-webcode/blob/release/87/modules/EnsEMBL/Draw/GlyphSet_transcript.pm#L1461). It will only affect items that have colour_key such as [gene.logic_name]_[gene.biotype]. Maybe @ens-ap5 will know?

**Comment by ens-st3** [comment]
Won't it also potentially affect $colour (https://github.com/Ensembl/ensembl-webcode/blob/release/87/modules/EnsEMBL/Draw/GlyphSet/TSE_transcript.pm#L43) ?

TSE_transcript is used for supporting evidence, for example:
http://www.ensembl.org/Homo_sapiens/Transcript/SupportingEvidence?db=core;g=ENSG00000128573;r=7:114414997-114693768;t=ENST00000403559

I can't find an example in plants though - can you check if if you have any ? The data for these comes from the supporting_feature and transcript_supporting_feature tables.

**Comment by Zhicheng-Liu** [comment]
I checked Metazoa and found the changes works for this page: http://metazoa.ensembl.org/Anopheles_gambiae/Transcript/SupportingEvidence?g=AGAP004707;r=2L:2358158-2431617;t=AGAP004707-RA

**Comment by ens-st3** [comment]
Confirmed OK with Ensembl as well. Thx

**Pull request merged**
