### PR TITLE
Added more hyperlinks for the Compara families

### PR DESCRIPTION
**Pull request by muffato**
- between pages
- link out to the source Panther and Hamap databases

Tested on my sandbox
http://enssand-02.internal.sanger.ac.uk:9073/Homo_sapiens/Gene/Family/Genes?cdb=compara;db=core;family=PTHR11289_SF0;g=ENSG00000139618;r=13:32315474-32400266 vs http://www.ensembl.org/Homo_sapiens/Gene/Family/Genes?cdb=compara;db=core;family=PTHR11289_SF0;g=ENSG00000139618;r=13:32315474-32400266

http://enssand-02.internal.sanger.ac.uk:9073/Multi/Family/Details?fm=PTHR11289_SF0 vs http://www.ensembl.org/Multi/Family/Details?fm=PTHR11289_SF0

### CODE REVIEW

**Comment by ens-ma7** [comment]
Hi Matthieu
The changes have been pushed to live as well.

Ridwan

**Comment by muffato** [comment]
Super, thank you !

**Comment by muffato** [comment]
Hi Ridwan,

Sorry but I've just realised this doesn't work on live: http://www.ensembl.org/Multi/Family/Details?fm=PTHR11289_SF0 has a link on the family ID to itself.
It does work on my sandbox: http://enssand-02.internal.sanger.ac.uk:9073/Multi/Family/Details?fm=PTHR11289_SF0
Maybe something has to be repacked because I've changed DEFAULTS.INI ?

**Comment by ens-ma7** [comment]
Hi Matthieu
I did a big restart of the live servers and this fixed it. can you please check and let me know if the changes are not there.
Ridwan

**Comment by muffato** [comment]
Great, thank you !!
Enjoy the Christmas break !

**Pull request merged**
