### PR TITLE
Update eQTL track info text

### PR DESCRIPTION
**Pull request by msmanoj**
## Description
Updated the track info from:
"Complete set of eQTL correlation statistics as computed by the GTEx consortium on<platelet> samples. Provided to Ensembl by the EBI eQTL catalog. The GTEx Consortium. Science. 8 May 2015: Vol 348 no. 6235 pp 648-660. DOI: 10.1126/science.1262110. PMID: 25954001"

To:

"Complete set of eQTL correlation statistics as computed on <platelet> samples. Provided to Ensembl by the EBI eQTL catalog (www.ebi.ac.uk/eqtl)"

## Views affected
http://ves-hx2-75.ebi.ac.uk:42229/Homo_sapiens/Gene/Regulation?g=ENSG00000139618;r=13:32315086-32400268

## Related JIRA Issues (EBI developers only)

https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6116

### CODE REVIEW

**Comment by ens-st3** [comment]
Can you add a hyperlink to www.ebi.ac.uk/eqtl ?

**Comment by msmanoj** [comment]
> Can you add a hyperlink to [www.ebi.ac.uk/eqtl](http://www.ebi.ac.uk/eqtl) ?

@ens-st3  - that's done. Please check again.

**Comment by ens-st3** [comment]
The code is reverted, I guess you're using it for something else. Happy to take your word on this

**Review by ens-st3 — APPROVED** [review]

**Comment by msmanoj** [comment]
> The code is reverted, I guess you're using it for something else. Happy to take your word on this

Hi @ens-st3 - Sorry, I didn't notice this comment before merging and yes, I was using the sandbox for a different task. This change is now live and it works fine.

**Pull request merged**
