### PR TITLE
Fix minor issue with empty object

### PR DESCRIPTION
**Pull request by ens-lgil**
If possible we would like to push this fix to master as well

### CODE REVIEW

**Comment by ens-ap5** [comment]
Hi Laurent - To get the fix onto master you'd need to make the pull request against postreleasefix/91, but it doesn't look like it's been created yet.

**Comment by ens-lgil** [comment]
@ens-ap5 should I create the branch on my repo then ?

**Comment by ens-ap5** [comment]
No - we produce it automatically, I think, using one of our git hooks. I’ll ask the new paladins when they get back from lunch, since Harpreet is no longer in charge!

Anne

**Comment by ens-ap5** [comment]
As we don't have the postreleasefix branch in place yet and this is a simple commit, we'll merge it into release/91 and manually cherry-pick it onto master.

**Comment by ens-lgil** [comment]
Thank you Anne!

**Pull request merged**
